WARNING | Неверный тип данных для объекта Runner | 2024-11-05 03:40:55,880
Traceback (most recent call last):
  File "C:\Users\dens7\PycharmProjects\pythonProject\.venv\module_12\tests_12_4.py", line 72, in test_run
    r2 = Runner(10, 10)
  File "C:\Users\dens7\PycharmProjects\pythonProject\.venv\module_12\tests_12_4.py", line 14, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
WARNING | Неверная скорость для Runner | 2024-11-05 03:40:55,882
Traceback (most recent call last):
  File "C:\Users\dens7\PycharmProjects\pythonProject\.venv\module_12\tests_12_4.py", line 62, in test_walk
    r1 = Runner('Вася', -5)
  File "C:\Users\dens7\PycharmProjects\pythonProject\.venv\module_12\tests_12_4.py", line 19, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
